[package]
name = "p1"
version = "0.1.0"
edition = "2021"  # You can update this to "2024" if you prefer

[dependencies]
chacha20poly1305 = "0.10"
scrypt = { version = "0.11", default-features = false }
rand = "0.8"

